
"""
PCAP-replay Traffic Generator for T-Rex -> Tofino (Translator)

Reads DTA telemetry packets from a PCAP file (generated by the reporter),
modifies the MAC addresses for the current testbed, and replays them
to the Tofino switch running the Translator P4 program.
Captures the returning packets (containing the QoE classification result).
"""

import sys
import os
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__),
                                'trex_client', 'interactive'))

from trex.stl.api import *
from scapy.all import rdpcap, Ether, IP, UDP

tx_port = 0
rx_port = 1

TREX_TX_MAC = "10:70:fd:30:80:d0"  # ens102f0np0 - Port 2
TREX_RX_MAC = "10:70:fd:30:80:d1"  # ens102f1np1 - Port 3
TOFINO_MAC = "D0:77:CE:2B:20:50"

TREX_RX_IP = "192.168.100.2"

SYNC_PORT = 4521
ASYNC_PORT = 4527

INPUT_PCAP = '/home/elmerd/trex_tofino_reply.pcap'
OUTPUT_PCAP = '/home/elmerd/trex_tofino_translator_reply.pcap'
DTA_UDP_PORT = 40040

def load_dta_pcap(pcap_file):
    """Load PCAP and extract DTA packets, rewriting MACs for replay."""
    print(f"Loading PCAP: {pcap_file}")
    packets = rdpcap(pcap_file)
    dta_pkts = []
    
    for pkt in packets:
        if UDP in pkt and pkt[UDP].dport == DTA_UDP_PORT:
            # Modify MACs to route from TRex TX to Tofino
            pkt[Ether].src = TREX_TX_MAC
            pkt[Ether].dst = TOFINO_MAC
            
            # Force Scapy to recalculate checksums
            if IP in pkt:
                del pkt[IP].chksum
            del pkt[UDP].chksum
            
            dta_pkts.append({
                'time': float(pkt.time),
                'pkt': pkt
            })
            
    print(f"Found {len(dta_pkts)} DTA packets out of {len(packets)} total packets.")
    return dta_pkts

def compute_timing(packets):
    """Compute inter-packet gaps (in microseconds)."""
    result = []
    for i, item in enumerate(packets):
        if i == 0:
            gap_us = 0.0
        else:
            gap_us = (item['time'] - packets[i - 1]['time']) * 1e6
        result.append((item['pkt'], gap_us))
    return result

def build_streams(timed_packets):
    """Build chained T-Rex STL streams for continuous replay."""
    streams = []
    for i, (pkt, gap_us) in enumerate(timed_packets):
        isg_us = gap_us if gap_us > 0 else 0
        streams.append({
            'name': f"dta_{i}",
            'pkt': pkt,
            'isg': isg_us
        })

    stl_streams = []
    for i, s in enumerate(streams):
        next_name = streams[(i + 1) % len(streams)]['name']
        stl_stream = STLStream(
            name=s['name'],
            packet=STLPktBuilder(pkt=s['pkt']),
            mode=STLTXSingleBurst(total_pkts=1),
            isg=s['isg'],
            next=next_name,
            self_start=(i == 0),
            action_count=0,
        )
        stl_streams.append(stl_stream)

    return stl_streams

if not os.path.exists(INPUT_PCAP):
    print(f"Error: Input PCAP not found at {INPUT_PCAP}")
    sys.exit(1)

dta_packets = load_dta_pcap(INPUT_PCAP)
if not dta_packets:
    print("No DTA packets found to replay. Exiting.")
    sys.exit(1)

timed = compute_timing(dta_packets)
stl_streams = build_streams(timed)

c = STLClient(username="trex", server="127.0.0.1",
              sync_port=SYNC_PORT, async_port=ASYNC_PORT, verbose_level="error")

try:
    c.connect()
    c.reset(ports=[tx_port, rx_port])

    print(f"\n{'=' * 60}")
    print(f"Translator Testing: DTA Replay")
    print(f"{'=' * 60}")
    print(f"TX: T-Rex Port {tx_port} ({TREX_TX_MAC}) --> Tofino ({TOFINO_MAC})")
    print(f"RX: Tofino --> T-Rex Port {rx_port} ({TREX_RX_MAC})")
    print(f"Replaying {len(dta_packets)} DTA packets.")
    print(f"{'=' * 60}")

    c.set_service_mode(ports=[rx_port])

    print("Starting capture on RX port...")
    capture = c.start_capture(
        rx_ports=[rx_port],
        mode='cyclic',
        limit=int(1e5)
    )

    # Keepalive on RX port (CRITICAL - prevents Arista loop)
    print(f"Starting keepalive on RX port {rx_port} to teach Arista the MAC...")
    keepalive_pkt = (
        Ether(src=TREX_RX_MAC, dst="ff:ff:ff:ff:ff:ff") /
        IP(src=TREX_RX_IP, dst="255.255.255.255") /
        UDP(sport=12345, dport=12345) /
        Raw(load="keepalive")
    )
    keepalive_stream = STLStream(
        packet=STLPktBuilder(pkt=keepalive_pkt),
        mode=STLTXCont(pps=5)
    )
    c.add_streams(keepalive_stream, ports=[rx_port])
    c.start(ports=[rx_port], force=True)
    time.sleep(2)
    print("Arista MAC learning done.")

    c.add_streams(stl_streams, ports=[tx_port])

    duration = 10
    print(f"\nSending DTA traffic for {duration} seconds...")
    c.start(ports=[tx_port], force=True)

    for i in range(duration):
        time.sleep(1)
        stats = c.get_stats()
        tx_pkts = stats[tx_port].get("opackets", 0)
        rx_pkts = stats[rx_port].get("ipackets", 0)
        print(f"  [{i + 1:2d}s] TX: {tx_pkts:>10,} pkts  RX: {rx_pkts:>10,} pkts")

    c.stop(ports=[tx_port, rx_port])
    print("Traffic stopped.")
    time.sleep(1)

    c.stop_capture(capture['id'], OUTPUT_PCAP)
    print(f"Capture saved to {OUTPUT_PCAP}")

    stats = c.get_stats()
    print(f"\n{'FINAL STATS':=^60}")
    print(f"TX packets: {stats[tx_port].get('opackets', 0):,}")
    print(f"RX packets: {stats[rx_port].get('ipackets', 0):,}")

    if os.path.exists(OUTPUT_PCAP):
        file_size = os.path.getsize(OUTPUT_PCAP)
        print(f"\n[SUCCESS] Packets captured! File size: {file_size} bytes")

except Exception as e:
    print(f"Error: {e}")
    import traceback
    traceback.print_exc()

finally:
    try:
        c.stop(ports=[tx_port, rx_port])
        c.set_service_mode(ports=[rx_port], enabled=False)
    except Exception:
        pass
    c.disconnect()
    print("Disconnected.")