#let abbreviations() = (
  (
    key: "ml",
    short: "ML",
    plural: "",
    long: "Machine Learning",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "ai",
    short: "AI",
    plural: "",
    long: "Artificial Intelligence",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "qoe",
    short: "QoE",
    plural: "",
    long: "Quality of Experience",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "vqa",
    short: "VQA",
    plural: "",
    long: "Video Quality Assessment",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "kpi",
    short: "KPI",
    plural: "KPIs",
    long: "Key Performance Indicator",
    longplural: "Key Performance Indicators",
    description: none,
    group: "",
  ),
  (
    key: "itu",
    short: "ITU",
    plural: "",
    long: "International Telecommunication Union",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "uhd",
    short: "UHD",
    plural: "",
    long: "Ultra-High-Definition",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "psnr",
    short: "PSNR",
    plural: "",
    long: "Peak Signal-to-Noise Ratio",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "ssim",
    short: "SSIM",
    plural: "",
    long: "Structural Similarity Index",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "ema",
    short: "EMA",
    plural: "",
    long: "Exponential Moving Average",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "mat",
    short: "MAT",
    plural: "MATs",
    long: "Match-Action Table",
    longplural: "Match-Action Tables",
    description: none,
    group: "",
  ),
  (
    key: "tcam",
    short: "TCAM",
    plural: "",
    long: "Ternary Content-Addressable Memory",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "dta",
    short: "DTA",
    plural: "",
    long: "Data-Plane Telemetry Architecture",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "asic",
    short: "ASIC",
    plural: "",
    long: "Application-Specific Integrated Circuit",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "dag",
    short: "DAG",
    plural: "",
    long: "Directed Acyclic Graph",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "iat",
    short: "IAT",
    plural: "",
    long: "Inter-Arrival Time",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "bwe",
    short: "BWE",
    plural: "",
    long: "Bandwidth Estimate",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "sdn",
    short: "SDN",
    plural: "",
    long: "Software-Defined Networking",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "bfrt",
    short: "BFRT",
    plural: "",
    long: "Barefoot Runtime",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "rf",
    short: "RF",
    plural: "",
    long: "Random Forest",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "pcap",
    short: "PCAP",
    plural: "",
    long: "Packet Capture",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "udp",
    short: "UDP",
    plural: "",
    long: "User Datagram Protocol",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "mac",
    short: "MAC",
    plural: "",
    long: "Media Access Control",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "ip",
    short: "IP",
    plural: "",
    long: "Internet Protocol",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "rdma",
    short: "RDMA",
    plural: "",
    long: "Remote Direct Memory Access",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "sram",
    short: "SRAM",
    plural: "",
    long: "Static Random-Access Memory",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "vliw",
    short: "VLIW",
    plural: "",
    long: "Very Long Instruction Word",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "qos",
    short: "QoS",
    plural: "",
    long: "Quality of Service",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "qod",
    short: "QoD",
    plural: "",
    long: "Quality of Delivery",
    longplural: "",
    description: none,
    group: "",
  ),
  (
    key: "dpi",
    short: "DPI",
    plural: "",
    long: "Deep Packet Inspection",
    longplural: "",
    description: none,
    group: "",
  ),
)
