#import "../lib.typ": *
#let related_work() = [
  #set par(first-line-indent: 1em, spacing: 1.2em, justify: true)

  == Quality of Experience Modeling

  Traditional approaches to #abbr("qoe") modeling have relied on subjective user studies and objective mathematical models to quantify end-user satisfaction @itu_g1011_qoe_assessment @chikkerur_objective_video_quality_assessment. Subjective methods, while considered the gold standard for accuracy, are expensive, time-intensive, and fundamentally impractical for deployment in real-world, large-scale network environments @duanmu_qoe_index_streaming_video . Objective metrics such as Peak Signal-to-Noise Ratio (#abbr("psnr")) @huynh_thu_scope_validity_psnr and the Structural Similarity Index (#abbr("ssim")) @wang_ssim_image_quality_assessment offer computational efficiency but have been shown to correlate poorly with actual human perception, particularly under complex network impairment conditions @wolf_psnr_video_sequence.

  On the other hand, with the adoption of end-to-end encryption (e.g., HTTPS, QUIC) for multimedia delivery, Deep Packet Inspection (#abbr("dpi")) and payload-based video quality analysis are no longer viable. Consequently, recent literature has pivoted towards inferring #abbr("qoe") metrics directly from encrypted network traffic patterns. A significant challenge in this space is the absence of a universally accepted #abbr("qoe") measurement standard @bentaleb_survey_bitrate_adaptation; for instance, the ITU-T P.1203 model was validated only for specific content conditions, limiting its applicability to modern high-resolution streams.

  Frameworks such as ViCrypt @wassermann_vicrypt_video_qoe have demonstrated the feasibility of using #abbr("ml") to predict video #abbr("qoe") from network-layer features, establishing a strong baseline for passive, encrypted traffic monitoring. Further extending this, contemporary studies have utilized #abbr("ml") models to estimate key #abbr("qoe") indicators for encrypted DASH traffic in modern cellular networks @ml_qoe_dash_5g and live video conferencing platforms @estimating_qoe_mdpi. Research by Izima et al. @izima_video_quality_prediction has further explored #abbr("qoe") prediction under time-varying network loads, highlighting the importance of temporal dynamics in feature design. These works collectively establish that statistical network properties such as packet sizes, (#abbr("iat")), and jitter are strong predictors of application-level events like buffer depletion and stalling, forming the theoretical basis for the feature engineering in this thesis.

  == In-Network #abbr("ml")

  While ML-based #abbr("qoe") prediction is well-established, relying on end-host GPUs or external collector servers introduces non-trivial processing latency and limits scalability in high-throughput environments. Recent advancements in programmable data planes, specifically using the P4 language @p4_language_specification, have enabled the displacement of some monitoring and decision-making logic from the control plane to the data plane @marina_paper. This paradigm shift allows classification and telemetry tasks to execute at line rate, directly within the forwarding hardware, eliminating the round-trip cost of offloading decisions to a separate server.

  Executing complex #abbr("ml") models like #abbr("rf")s at line rate, however, requires specialized hardware mapping, as programmable ASICs such as the Intel Tofino do not natively support recursive branching or floating-point arithmetic. The pForest architecture @busse_grawitz_pforest_in_network_inference introduced the foundational concept of translating context-dependent decision trees into Match-Action Tables (#abbrpl("mat")) for in-network inference, demonstrating that tree traversal can be unrolled across sequential pipeline stages. Building upon this paradigm, frameworks like Planter @planter_paper have formalized and automated the mapping of a broad range of ensemble #abbr("ml") models, including #abbr("rf")s, gradient boosted trees, and support vector machines, into programmable switches, significantly lowering the barrier for in-network #abbr("ml") deployment. Other recent works have explored resource-efficient implementations of tree-based models using feature sharing and knowledge distillation @empowering_in_network_classification, reducing #abbr("tcam") pressure by sharing common decision nodes across trees. Hybrid approaches, such as IIsy @iisy_framework, partition the classification task between the data plane and a co-located control-plane agent, relaxing hardware constraints while preserving low-latency inference for the majority of traffic. These methodologies collectively provide the architectural foundation for our approach of translating a unified #abbr("rf") model into unrolled physical pipeline stages using Ternary Content-Addressable Memory (#abbr("tcam")).



  #figure(
    image("../assets/pipeline.png", width: 100%),
    caption: [The general architecture of a P4 switch. @empowering_in_network_classification],
  )

  == Benchmarking and Hardware Constraints

  Evaluating the performance of in-network #abbr("ml") models requires a rigorous understanding of the strict physical constraints imposed by programmable ASICs. Comprehensive surveys on in-network machine learning @in_network_ml_survey have characterized the fundamental bottlenecks of devices such as the Intel Tofino: available #abbr("sram") and #abbr("tcam") capacity, Very Long Instruction Word (VLIW) instruction slot budgets, and a hard limit on the number of physical pipeline stages. These constraints are not merely engineering inconveniences; they define a hard feasibility boundary that determines whether a given model can be compiled and deployed at all.

  Studies evaluating hybrid in-network classification frameworks, such as IIsy @iisy_framework, emphasize the complex, multi-dimensional trade-offs between a model's predictive accuracy and its hardware resource footprint, showing that naive model translation routinely exceeds available pipeline resources. Furthermore, because the Tofino architecture enforces a strict Directed Acyclic Graph (#abbr("dag")) for table execution, the recursive branching inherent in standard decision trees must be aggressively flattened before compilation @in_network_topology_survey. Feature selection therefore plays a dual role: beyond its conventional impact on statistical performance, it directly determines the #abbr("tcam") and #abbr("vliw") instruction budget consumed by each pipeline stage. Recent work by Xie et al. @empowering_in_network_classification has demonstrated that knowledge distillation can compress decision tree ensembles into shallower structures that respect these stage limits without significant accuracy loss. These findings directly motivate the benchmarking methodology adopted in this thesis, in which feature count, tree depth, and ensemble size are systematically swept to map the feasibility boundary on Tofino 2 hardware.
]
